import { Raleway } from "next/font/google";
import "./globals.css";
import Menu from "./componentes/menu";

const raleway = Raleway({
  subsets: ["latin"],
});

export const metadata = {
  title: "Conversores",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="´t-br">
      <body
        className={`${raleway.className} antialiased`}
      >
        <Menu />
        {children}
      </body>
    </html>
  );
}